let apartments = [
	{
		id: 1,
		street: '3471 Paseo De Brisas #32',
		city: 'Oceanside',
		state: 'CA',
		manager: 'Kadie',
		email: 'kadie@email.com',
		price: '$1,995',
		bedrooms: 2,
		bathrooms: 2,
		pets: 'yes',
		image:
			'https://images.cpmteam.com/3471-Paseo-De-Brisas-32-Oceanside-CA-92056-54473.jpg',
		user_id: 5,
	},
	{
		id: 2,
		street: '947 Aspen Court',
		city: 'Carlsbad',
		state: 'CA',
		manager: 'Erika',
		email: 'erika@email.com',
		price: '$2,795',
		bedrooms: 3,
		bathrooms: 2.5,
		pets: 'yes',
		image:
			'https://images.cpmteam.com/947-Aspen-Court-Carlsbad-CA-92011-52697.jpg',
		user_id: 6,
	},
	{
		id: 3,
		street: '1740 Fairlead',
		city: 'Carlsbad',
		state: 'CA',
		manager: 'Kadie',
		email: 'kadie@email.com',
		price: '$3,100',
		bedrooms: 3,
		bathrooms: 2.5,
		pets: 'yes',
		image: 'https://images.cpmteam.com/1740FairleadCarlsbadCA92011-54537.jpg',
		user_id: 5,
	},
	{
		id: 4,
		street: '1289 Shorebird',
		city: 'Carlsbad',
		state: 'CA',
		manager: 'Erika',
		email: 'erika@email.com',
		price: '$5,900',
		bedrooms: 4,
		bathrooms: 3.5,
		pets: 'yes',
		image:
			'https://images.cpmteam.com/1289ShorebirdLaneCarlsbadCA92011-54658.jpg',
		user_id: 6,
	},
	{
		id: 5,
		street: '2821 Rancho Rio Chico',
		city: 'Carlsbad',
		state: 'CA',
		manager: 'Amanda',
		email: 'amanda@email.com',
		price: '$5,500',
		bedrooms: 5,
		bathrooms: 4,
		pets: 'yes',
		image:
			'https://images.cpmteam.com/2821RanchoRioChicoCarlsbadCA92011-53962.jpg',
		user_id: 1,
	},
	{
		id: 6,
		street: '3384 Morning View Drive',
		city: 'Oceanside',
		state: 'CA',
		manager: 'Amanda',
		email: 'amanda@email.com',
		price: '$3,200',
		bedrooms: 4,
		bathrooms: 2.5,
		pets: 'yes',
		image:
			'https://images.cpmteam.com/3384-Morning-View-Drive-Oceanside-CA-92058-11763.jpg',
		user_id: 1,
	},
	{
		id: 7,
		street: '5320 Mead Street',
		city: 'Oceanside',
		state: 'CA ',
		manager: 'April',
		email: 'april@email.com',
		price: '$2,900',
		bedrooms: 3,
		bathrooms: 2.5,
		pets: 'no',
		image:
			'https://images.cpmteam.com/5320-Mead-St-Oceanside-CA-92056-22605.jpg',
		user_id: 2,
	},
	{
		id: 8,
		street: '557 Sonoma Street',
		city: 'San Marcos',
		state: 'CA',
		manager: 'April',
		email: 'april@email.com',
		price: '$2,900',
		bedrooms: 3,
		bathrooms: 2.5,
		pets: 'yes',
		image:
			'https://images.cpmteam.com/557-Sonoma-St-San-Marcos-CA-92078-54580.jpg',
		user_id: 2,
	},
	{
		id: 9,
		street: '190 Belflora',
		city: 'Oceanside',
		state: 'CA',
		manager: 'Paula',
		email: 'paula@email.com',
		price: '$2,650',
		bedrooms: 3,
		bathrooms: 2.5,
		pets: 'yes',
		image:
			'https://images.cpmteam.com/190-Belflora-Oceanside-CA-92056-29210.jpg',
		user_id: 3,
	},
	{
		id: 10,
		street: '817 Kalpati #111',
		city: 'Carlsbad',
		state: 'CA',
		manager: 'Paula',
		email: 'paula@email.com',
		price: '$2,600',
		bedrooms: 2,
		bathrooms: 2,
		pets: 'yes',
		image: 'https://images.cpmteam.com/817Kalpati111CarlsbadCA92008-47808.jpg',
		user_id: 3,
	},
	{
		id: 11,
		street: '1024 Laguna Dr. #11',
		city: 'Carlsbad',
		state: 'CA',
		manager: 'Vickie',
		email: 'vickie@email.com',
		price: '$2,200',
		bedrooms: 2,
		bathrooms: 2,
		pets: 'yes',
		image:
			'https://images.cpmteam.com/1024-Laguna-Dr-11-Carlsbad-CA-92008-16088.jpg',
		user_id: 4,
	},
	{
		id: 12,
		street: '2541 Jefferson St. #14',
		city: 'Carlsbad',
		state: 'CA',
		manager: 'Vickie',
		email: 'vickie@email.com',
		price: '$2,150',
		bedrooms: 2,
		bathrooms: 1.5,
		pets: 'yes',
		image:
			'https://images.cpmteam.com/2541-Jefferson-St-Carlsbad-CA-92008-38923.jpg',
		user_id: 4,
	},
	{
		id: 13,
		street: '3515 Roosevelt St. #32',
		city: 'Carlsbad',
		state: 'CA',
		manager: 'Vickie',
		email: 'vickie@email.com',
		price: '$1,975',
		bedrooms: 2,
		bathrooms: 2,
		pets: 'no',
		image:
			'https://images.cpmteam.com/35153527353935513563RooseveltStCarlsbadCA92008-47554.jpg',
		user_id: 4,
	},
]

export default apartments
